import Config

# Configure your database
# DB config đọc từ env (có fallback để chạy local bằng `mix` vẫn được).
# Khi chạy bằng Docker, docker-compose set DB_HOST=db, DB_USER/DB_PASS=postgres.
config :food_street, FoodStreet.Repo,
  username: System.get_env("DB_USER", "pancake"),
  password: System.get_env("DB_PASS", ""),
  hostname: System.get_env("DB_HOST", "localhost"),
  database: System.get_env("DB_NAME", "food_street_dev"),
  port: String.to_integer(System.get_env("DB_PORT", "5432")),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :food_street, FoodStreetWeb.Endpoint,
  # Mặc định bind loopback (local). Trong Docker set PHX_IP=0.0.0.0 để host
  # truy cập được qua port mapping.
  http: [
    ip:
      case System.get_env("PHX_IP") do
        nil -> {127, 0, 0, 1}
        ip -> ip |> String.split(".") |> Enum.map(&String.to_integer/1) |> List.to_tuple()
      end
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "845TqR94f3NIwZXSf+eqByjf7O8ZRu3kRhK6815mQwRrmNYydxmKoT049RxkJ2KQ",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :food_street, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
